### ISSUE TITLE
README.md : Specify environment dependency to Dokan library

### ISSUE THREAD

**Issue by ifrh** [dokan-dev/dokan-sshfs#13]
You write that Dokan SSHFS depends on
Dokan library [https://github.com/dokan-dev/dokany](https://github.com/dokan-dev/dokany)
for that project is written 
- Dokany is a fork of Dokan 0.6.0 with bug fixes, clean change history and updated to build with latest tools.
- Because the original Dokan Legacy (< 0.6.0) project is no longer maintained.
- Since version 0.8.0, dokany break dokan API compatibility. 

Please specify in your own README.md which Dokany Version you support for which Windows-Version.

**Comment by Liryna** [comment]
Hi @ifrh ,

I changed the link to point directly to the dokan version 1.0.1 https://github.com/dokan-dev/dokan-sshfs/commit/b4d90abe18815a58efac4a58d5d04e8f0838840a

Windows version supported is the version supported by the dependency explained here https://github.com/dokan-dev/dokan-sshfs#environment

**Comment by ifrh** [comment]
Thank you very much!
