### ISSUE TITLE
Connection issue

### ISSUE THREAD

**Issue by zilti** [dokan-dev/dokan-sshfs#14]
I have the latest dokany version, and downloaded dokan-sshfs. All dokan-sshfs tells me is that it couldn't connect. Putty at the same time has no problem connecting to the same server with the same auth data (I used password auth).

**Comment by Liryna** [comment]
Hi @zilti ,

I don't think this is related to windows 10 but more to an authentication issue. 
Consider using sshfs, it probably supports you server authentication.
https://github.com/Foreveryone-cz/win-sshfs

**Comment by zilti** [comment]
Yes, that worked. Thanks!
