### ISSUE TITLE
Does it only work with dokan 1.0.1?

### ISSUE THREAD

**Issue by wwqgtxx** [dokan-dev/dokan-sshfs#19]
dokan 1.0.1 was released on 4 Nov 2016, It is a very old version, could `dokan-dev` support the newest `dokan 1.2.0.1000` to work better in win10?

**Comment by Liryna** [comment]
Hi @wwqgtxx ,

I just made the update 👍 https://github.com/dokan-dev/dokan-sshfs/commit/56a2184217c6ac4ff1f8c196ccd8f3b40eed10cd

**Comment by wwqgtxx** [comment]
Thanks, and it still had a old bug #15 ,would that problem fix too. Maybe shoud upgrade `Tamir.SharpSSH` or replace it.
