### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by WhiteAbeLincoln** [dokan-dev/dokan-sshfs#3]
It would be nice to have some build instructions. Currently there are three different projects in the repository, and I'm not sure how they connect.

**Comment by smac89** [comment]
@WhiteAbeLincoln
- Download the project (simply use git clone for this)
- Open the directory: `dokan-sshfs\DokanSSHFS`
- Open `DokanSSHFS.csproj` in visual studio
- At the top of visual studio, click build > Configuration manager
- Select x86 for platform and set Configuration to Release
- Close it
- Click build again and this time choose `Build Solution`
- After it's done, you can find the executable in `dokan-sshfs\DokanSSHFS\bin\x86\Release`

**Comment by Liryna** [comment]
Thank you @smac89 
Added with https://github.com/dokan-dev/dokan-sshfs/commit/487d3a4fbb3dda629bde9ff8a277c0f9ced23677
