### ISSUE TITLE
Distribute installer

### ISSUE THREAD

**Issue by dustymabe** [dokan-dev/dokan-sshfs#5]
dokany distributes their .exe file (I assume this is an installer)  with their release:
https://github.com/dokan-dev/dokany/releases

Is there any way we could get a built installer distributed? Would love to try this out.

**Comment by Liryna** [comment]
Unfortunatly, this project is only here as an exemple of using dokany.
We have not plan to have a system of release/installer for now.

If you want to try, I would propose you to try https://github.com/dimov-cz/win-sshfs It is a more advanced project and it use dokany also.
