### ISSUE TITLE
Where is the exe?

### ISSUE THREAD

**Issue by randomessence** [dokan-dev/dokan-sshfs#7]
Is there no pre built binary available to work with 0.8.0?

**Comment by Liryna** [comment]
See https://github.com/dokan-dev/dokan-sshfs/issues/5

**Comment by randomessence** [comment]
Then the readme should be updated to reflect that position. My question was a direct result of reading that readme.

https://github.com/dokan-dev/dokan-sshfs#how-to-use

**Comment by Liryna** [comment]
Ok I agree, fixed by https://github.com/dokan-dev/dokan-sshfs/commit/487d3a4fbb3dda629bde9ff8a277c0f9ced23677
