### ISSUE TITLE
No dokan.dll

### ISSUE THREAD

**Issue by gdh1995** [dokan-dev/dokan-sshfs#9]
There's only dokan1.dll after I installed dokany.

Every step I tried to dokan-sshfs raised some crashes - It's too hard to just run it.

**Comment by Liryna** [comment]
dokan-sshfs is only compatible with dokan 0.7.4 for now.
Please remove dokan 1.0.0 that you installed and install 0.7.4

**Comment by gdh1995** [comment]
Okay.

**Comment by gdh1995** [comment]
Is dokany 0.8.0 supported?

**Comment by Liryna** [comment]
No it is not, dokan-sshfs is not maintained :cry:
